FROM node:18-alpine as build

COPY package.json package-lock.json ./

RUN npm ci && mkdir /gym-app && mv ./node_modules ./gym-app/

WORKDIR /gym-app

COPY . .

RUN npm run build


FROM nginx:1.25-alpine

COPY nginx.default.conf /etc/nginx/conf.d/default.conf 

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /gym-app/dist/gym-diary /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]